imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: "%debug_toolbar%"
    intercept_redirects: "%debug_redirects%"
    #intercept_redirects: true

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        chromephp:
            type:   chromephp
            level:  info

assetic:
    use_controller: "%use_assetic_controller%"

swiftmailer:
    #disable_delivery: true
    delivery_address: afetisov@gmail.com

#old_sound_rabbit_mq:
#    connections:
#        default:
#            host:     %rabbitmq_host%
#            port:     %rabbitmq_port%
#            user:     %rabbitmq_user%
#            password: %rabbitmq_password%
#            vhost:    %rabbitmq_vhost%
#            lazy:     true
#    producers:
#        split_file:
#            connection:       default
#            exchange_options: { name: 'file_nodes', type: direct }
#    consumers:
#            read_node:
#                connection:       default
#                exchange_options: { name: 'file_nodes', type: direct }
#                queue_options:    { name: 'file_nodes' }
#                callback:         process_node
