parameters:
#    bro_demo.example.class: BRO\DemoBundle\Example

services:
#    bro_demo.example:
#        class: %bro_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
