        
services:
    bro_user.registration.form.type:
        class: BRO\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: bro_user_registration }
    
    bro_user.profile.form.type:
        class: Application\Sonata\UserBundle\Form\Type\ProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_sonata_user_profile }
            
    bro_user.form.handler.profile:
        class: Application\Sonata\UserBundle\Form\Handler\ProfileFormHandler
        arguments: ["@sonata.user.profile.form", "@request", "@fos_user.user_manager"]
        scope: request
        public: false